services:
  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    command: sh -c "sleep 5 && npm start"
    networks:
      - networkA
  postgres:
    build:
      context: ./database
    env_file:
      - ./database/.env
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-storage:/var/lib/postgressql/data
    networks:
      - networkA
volumes:
  postgres-storage:

networks:
  networkA: